name: "Build executables"

on:
  push:
    branches: [ main ]

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          python_arch: 'x64'
          spec: 'wledvideo.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'WLED-video for Windows (x64)'
