name: "Build executables"

on:
  push:
    branches: [ feature* ]

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'wledvideo.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'WLED-video for Windows (x64)'

  pyinstaller-build-macos:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'wledvideo.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'WLED-video for Mac OS (x64)'

  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'wledvideo.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'WLED-video for Linux (x64)'

